### ISSUE TITLE
Presentasi/Demo Milestone 1 (M1)

### ISSUE THREAD

**Issue by taruma** [hidrokit/hidrokit#161]
Beberapa poin yang dipresentasikan:
- [x] Demo Buku Analisis Data Hujan (#145)
- [x] Buku untuk modul statistik dasar (#158)
- [x] Buku untuk modul uji outlier (#151)
- [x] Progress dan Milestone selama 2 minggu terakhir.
